# Generated by Django 4.2.11 on 2024-09-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_image",
            field=models.ImageField(blank=True, null=True, upload_to="courses_images/"),
        ),
    ]
