# Generated by Django 5.0.4 on 2024-11-18 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capitol",
            options={"ordering": ["position"]},
        ),
        migrations.AlterModelOptions(
            name="subcapitol",
            options={"ordering": ["position"]},
        ),
        migrations.RemoveField(
            model_name="quizz",
            name="chapter",
        ),
        migrations.RemoveField(
            model_name="quizz",
            name="title",
        ),
        migrations.AddField(
            model_name="capitol",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Published"),
        ),
        migrations.AddField(
            model_name="capitol",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="course_image",
            field=models.ImageField(
                blank=True,
                default="courses_images/img.jpeg",
                upload_to="courses_images/",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Published"),
        ),
        migrations.AddField(
            model_name="quizz",
            name="subchapter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="teacher_dashboard.subcapitol",
            ),
        ),
        migrations.AddField(
            model_name="subcapitol",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subcapitol",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Published"),
        ),
        migrations.AddField(
            model_name="subcapitol",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                (
                    "quizz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="teacher_dashboard.quizz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="teacher_dashboard.question",
                    ),
                ),
            ],
        ),
    ]
