# Generated by Django 4.2.11 on 2024-09-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_dashboard", "0002_course_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(
                blank=True,
                default="courses_images/img.jpg",
                upload_to="courses_images/",
            ),
        ),
    ]
