# Generated by Django 5.0.4 on 2024-11-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "teacher_dashboard",
            "0002_alter_capitol_options_alter_subcapitol_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="quizz",
            name="title",
            field=models.CharField(default="Q1", max_length=100),
        ),
    ]
