# Generated by Django 5.0.4 on 2024-11-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_dashboard", "0003_quizz_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(
                related_name="courses", to="teacher_dashboard.category"
            ),
        ),
        migrations.DeleteModel(
            name="CourseCategory",
        ),
    ]
