# Generated by Django 5.0.4 on 2024-11-22 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_dashboard", "0004_alter_category_options_course_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="categories",
        ),
    ]
