# Generated by Django 5.0.4 on 2024-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher_dashboard", "0007_course_categories_delete_coursecategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[("language", "Language"), ("general", "General")],
                default="general",
                max_length=50,
            ),
        ),
    ]
