# Generated by Django 4.2.11 on 2024-12-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_expertiseareaadmin_alter_expertisearea_options_and_more'),
        ('teacher_dashboard', '0008_category_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_exercises', to='user.teacher')),
                ('subchapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='teacher_dashboard.subcapitol')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='IndependentExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('medium', 'Medium'), ('advanced', 'Advanced')], default='beginner', max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='independent_exercises', to='user.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.AddField(
            model_name='independentexercise',
            name='programming_languages',
            field=models.ManyToManyField(related_name='independent_exercises', to='teacher_dashboard.programminglanguage'),
        ),
    ]
