# Generated by Django 4.2.11 on 2024-12-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('teacher_dashboard', '0009_courseexercise_independentexercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('input_data', models.JSONField(help_text='Input-ul pentru test (ex: [2, 3]).')),
                ('expected_output', models.JSONField(help_text='Output-ul așteptat pentru acest input.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.RemoveField(
            model_name='independentexercise',
            name='programming_languages',
        ),
        migrations.AddField(
            model_name='courseexercise',
            name='programming_language',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('PHP', 'PHP')], default='Python', help_text='Limbajul de programare folosit pentru acest exercitiu.', max_length=50),
        ),
        migrations.AddField(
            model_name='independentexercise',
            name='programming_language',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++'), ('Ruby', 'Ruby'), ('PHP', 'PHP')], default='Python', help_text='Limbajul de programare folosit pentru acest exercitiu.', max_length=50),
        ),
        migrations.DeleteModel(
            name='ProgrammingLanguage',
        ),
    ]
