# Generated by Django 4.2.11 on 2024-12-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0010_testcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexercise',
            name='reference_solution',
            field=models.TextField(blank=True, help_text='Codul soluției de referință pentru acest exercițiu.', null=True),
        ),
        migrations.AddField(
            model_name='independentexercise',
            name='reference_solution',
            field=models.TextField(blank=True, help_text='Codul soluției de referință pentru acest exercițiu.', null=True),
        ),
    ]
