# Generated by Django 4.2.11 on 2024-12-11 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0011_courseexercise_reference_solution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text='Input for the test case')),
                ('expected_output', models.JSONField(help_text='Expected output for the test case')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_test_cases', to='teacher_dashboard.independentexercise')),
            ],
        ),
    ]
