# Generated by Django 4.2.11 on 2024-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0012_teachertestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachertestcase',
            name='passed',
            field=models.BooleanField(default=False, help_text='Indica dacă testul a fost trecut.'),
        ),
    ]
