# Generated by Django 4.2.11 on 2024-12-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0013_teachertestcase_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachertestcase',
            name='expected_output',
        ),
        migrations.RemoveField(
            model_name='teachertestcase',
            name='input_data',
        ),
        migrations.AddField(
            model_name='teachertestcase',
            name='test_case',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_test_cases', to='teacher_dashboard.testcase'),
        ),
    ]
