# Generated by Django 4.2.11 on 2025-02-08 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_expertiseareaadmin_alter_expertisearea_options_and_more'),
        ('teacher_dashboard', '0014_remove_teachertestcase_expected_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='exercise',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='teacher_dashboard.independentexercise'),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='user.teacher'),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='programming_language',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++'), ('C', 'C'), ('PHP', 'PHP')], default='Python', help_text='Limbajul de programare folosit pentru acest exercitiu.', max_length=50),
        ),
        migrations.AlterField(
            model_name='independentexercise',
            name='programming_language',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C++', 'C++'), ('C', 'C'), ('PHP', 'PHP')], default='Python', help_text='Limbajul de programare folosit pentru acest exercitiu.', max_length=50),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.JSONField(help_text='Input-ul pentru test (ex: 2 3).'),
        ),
    ]
