# Generated by Django 4.2.11 on 2025-03-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0015_testcase_exercise_alter_courseexercise_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='courseexercise',
            name='programming_language',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP')], default='Python', help_text='Limbajul de programare folosit pentru acest exercitiu.', max_length=50),
        ),
        migrations.AlterField(
            model_name='independentexercise',
            name='programming_language',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('PHP', 'PHP')], default='Python', help_text='Limbajul de programare folosit pentru acest exercitiu.', max_length=50),
        ),
    ]
