# Generated by Django 4.2.11 on 2025-04-09 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0016_course_is_finished_quizz_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Întrebare interviu')),
                ('answer', models.TextField(verbose_name='Model de răspuns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='teacher_dashboard.category')),
            ],
            options={
                'verbose_name_plural': 'Întrebări interviu',
            },
        ),
        migrations.DeleteModel(
            name='TeacherTestCase',
        ),
    ]
