# Generated by Django 4.2.11 on 2025-04-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_expertisearea_name_alter_frontuser_email_and_more'),
        ('teacher_dashboard', '0017_interviewquestion_delete_teachertestcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='user.teacher'),
            preserve_default=False,
        ),
    ]
