# Generated by Django 4.2.11 on 2025-04-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0018_interviewquestion_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
