# Generated by Django 4.2.11 on 2025-04-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0019_interviewquestion_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='category',
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='categories',
            field=models.ManyToManyField(related_name='questions', to='teacher_dashboard.category'),
        ),
    ]
