# Generated by Django 5.0.4 on 2024-11-29 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teacher_dashboard", "0008_category_category_type"),
        ("user", "0002_expertiseareaadmin_alter_expertisearea_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrolled_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The complete percentage of the course.",
                        max_digits=5,
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The final score of the student after finish the course.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="teacher_dashboard.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="user.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgressTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Scor pentru acest subcapitol",
                        max_digits=5,
                    ),
                ),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_trackers",
                        to="student_dashboard.enrollment",
                    ),
                ),
                (
                    "subchapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher_dashboard.subcapitol",
                    ),
                ),
            ],
            options={
                "ordering": ["subchapter__position"],
                "unique_together": {("enrollment", "subchapter")},
            },
        ),
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "attempted_on",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_results",
                        to="student_dashboard.progresstracker",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher_dashboard.question",
                    ),
                ),
            ],
        ),
    ]
