# Generated by Django 4.2.11 on 2024-09-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teacher_dashboard", "0001_initial"),
        ("user", "0001_initial"),
        ("student_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="progrescurs",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_progress",
                to="teacher_dashboard.course",
            ),
        ),
        migrations.AddField(
            model_name="progrescurs",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_progress",
                to="user.student",
            ),
        ),
        migrations.AddField(
            model_name="inscriere",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="teacher_dashboard.course",
            ),
        ),
        migrations.AddField(
            model_name="inscriere",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="user.student",
            ),
        ),
    ]
