# Generated by Django 4.2.11 on 2024-12-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
