# Generated by Django 4.2.11 on 2025-04-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0002_quizresult_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='final_score',
        ),
        migrations.RemoveField(
            model_name='progresstracker',
            name='score',
        ),
    ]
