# Generated by Django 4.2.11 on 2025-04-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0004_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresstracker',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
