"""
Django settings example for Licenta project.

IMPORTANT: Copy this file to settings.py and fill in your own values.
Never commit settings.py to version control - it contains sensitive data.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generate a new secret key: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'
SECRET_KEY = 'your-secret-key-here-change-this-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user.apps.UserConfig',
    'student_dashboard.apps.StudentDashboardConfig',
    'teacher_dashboard.apps.TeacherDashboardConfig',
    'visitator.apps.VisitatorConfig',
    'bootstrap5',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_recaptcha',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'Licenta.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'user' / 'templates' / 'user' / 'teacher',
            BASE_DIR / 'user' / 'templates' / 'user' / 'student',
            BASE_DIR / 'templates',
            BASE_DIR / 'teacher_dashboard' / 'templates' / 'courses',
            BASE_DIR / 'teacher_dashboard' / 'templates' / 'exercises',
            BASE_DIR / 'teacher_dashboard' / 'templates' / 'interview_questions',
            BASE_DIR / 'teacher_dashboard' / 'templates' / 'statistics',
            BASE_DIR / 'user' / 'templates' / 'profile',
            BASE_DIR / 'visitator' / 'templates' / 'visitator',
            BASE_DIR / 'visitator' / 'templates' / 'exercises',
            BASE_DIR / 'visitator' / 'templates' / 'questions',
            BASE_DIR / 'student_dashboard' / 'templates' / 'course',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'user.context_processors.user_profile_urls',
            ],
        },
    },
]

WSGI_APPLICATION = 'Licenta.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# For development, you can use SQLite. For production, use PostgreSQL or MySQL.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# For PostgreSQL (uncomment and configure for production):
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'your_database_name',
#         'USER': 'your_db_user',
#         'PASSWORD': 'your_db_password',
#         'HOST': 'localhost',
#         'PORT': '5432',
#         'CONN_MAX_AGE': 600,
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'user.backends.EmailBackend',
]

AUTH_USER_MODEL = 'user.FrontUser'

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'static'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_URL = 'http://localhost:8000'

CRISPY_TEMPLATE_PACK = 'bootstrap5'

# reCAPTCHA Configuration
# Get your keys from: https://www.google.com/recaptcha/admin
RECAPTCHA_PUBLIC_KEY = 'your-recaptcha-public-key'
RECAPTCHA_PRIVATE_KEY = 'your-recaptcha-private-key'
RECAPTCHA_DOMAIN = 'localhost'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

# Email Configuration
# For development, you can use the console backend:
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# For production, use your email service:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'your-smtp-host'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'your-email@example.com'
EMAIL_HOST_PASSWORD = 'your-email-password'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'your-email@example.com'
ADMIN_EMAIL = 'admin@example.com'

# Media Files Configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

X_FRAME_OPTIONS = 'SAMEORIGIN'

# Caching Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 60,
    }
}

# Session Configuration
SESSION_COOKIE_AGE = 365 * 24 * 60 * 60  # 1 year
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# External API Keys (use environment variables in production)
# Stripe Configuration
STRIPE_SECRET_KEY = 'your-stripe-secret-key'
STRIPE_PUBLISHABLE_KEY = 'your-stripe-publishable-key'

# Judge0 API Configuration (for code execution)
# https://judge0.com/
JUDGE0_API_KEY = 'your-judge0-api-key'
