# Generated by Django 5.0.4 on 2024-08-06 12:02

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import user.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        error_messages={
                            "unique": "A user is already registered with this email address."
                        },
                        max_length=255,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ExpertiseArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("web_dev", "Web Development"),
                            ("mobile_dev", "Mobile App Development"),
                            ("data_science", "Data Science"),
                            ("cyber_security", "Cybersecurity"),
                            ("networking", "Networking"),
                            ("cloud_computing", "Cloud Computing"),
                            ("artificial_intelligence", "Artificial Intelligence"),
                            ("machine_learning", "Machine Learning"),
                            ("blockchain", "Blockchain"),
                            ("game_dev", "Game Development"),
                            ("ui_ux_design", "UI/UX Design"),
                            ("embedded_systems", "Embedded Systems"),
                            ("it_management", "IT Management"),
                            ("software_testing", "Software Testing"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "frontuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "occupation",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("self_employed", "Self employed"),
                            ("freelancer", "Freelancer"),
                            ("retired", "Retired"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=30,
                    ),
                ),
                (
                    "it_level",
                    models.CharField(
                        choices=[
                            ("just_started", "Just started (new to IT)"),
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="just_started",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
            bases=("user.frontuser",),
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "frontuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=35)),
                (
                    "academic_title",
                    models.CharField(
                        choices=[
                            ("professor", "Professor"),
                            ("associate_professor", "Associate Professor"),
                            ("assistant_professor", "Assistant Professor"),
                            ("lecturer", "Lecturer"),
                            ("graduate_student", "Graduate Student"),
                            ("professional", "Professional"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("activity_years", models.IntegerField(default=0)),
                ("resume", models.FileField(blank=True, upload_to="resumes/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "expertise_area",
                    models.ManyToManyField(blank=True, to="user.expertisearea"),
                ),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
            },
            bases=("user.frontuser",),
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
