# Generated by Django 5.0.4 on 2024-11-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertiseAreaAdmin",
            fields=[
                (
                    "expertisearea_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="user.expertisearea",
                    ),
                ),
            ],
            bases=("user.expertisearea",),
        ),
        migrations.AlterModelOptions(
            name="expertisearea",
            options={"verbose_name_plural": "Expertise areas"},
        ),
        migrations.AlterField(
            model_name="frontuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/poza.jpeg",
                upload_to="profile_pictures/",
            ),
        ),
    ]
