# Generated by Django 4.2.11 on 2024-09-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frontuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pictures/poza.jpeg",
                upload_to="profile_pictures/",
            ),
        ),
    ]
