# Generated by Django 4.2.11 on 2025-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_expertiseareaadmin_alter_expertisearea_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertisearea',
            name='name',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('mobile_dev', 'Mobile App Development'), ('data_science', 'Data Science'), ('cyber_security', 'Cybersecurity'), ('networking', 'Networking'), ('cloud_computing', 'Cloud Computing'), ('artificial_intelligence', 'Artificial Intelligence'), ('machine_learning', 'Machine Learning'), ('game_dev', 'Game Development'), ('ui_ux_design', 'UI/UX Design'), ('embedded_systems', 'Embedded Systems'), ('it_management', 'IT Management'), ('software_testing', 'Software Testing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='frontuser',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'Un utilizator este deja înregistrat cu această adresă de email.'}, max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='it_level',
            field=models.CharField(choices=[('just_started', 'Abia am început (nou în IT)'), ('beginner', 'Începător'), ('intermediate', 'Intermediar'), ('advanced', 'Avansat')], default='just_started', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='occupation',
            field=models.CharField(choices=[('student', 'Student'), ('employed', 'Angajat'), ('unemployed', 'Șomer'), ('self_employed', 'Liber profesionist/PFA'), ('freelancer', 'Freelancer'), ('retired', 'Pensionar'), ('others', 'Altele')], default='others', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_title',
            field=models.CharField(choices=[('professor', 'Profesor'), ('graduate_student', 'Student masterand/doctorand'), ('professional', 'Profesionist în domeniu'), ('other', 'Altele')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobat'), ('rejected', 'Respins')], default='pending', max_length=20),
        ),
    ]
