# Generated by Django 4.2.11 on 2025-05-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_expertisearea_name_alter_frontuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
    ]
